name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest

      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: vladislavgs/sausage-backend:latest
            build-args: |
              VERSION=${{ github.sha }}

        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: vladislavgs/sausage-frontend:latest

        - name: Push Backend-report to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: vladislavgs/sausage-backend-report:latest

  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub

      steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add nexus repo and push helm-chart
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push
          helm repo add chartmuseum ${{ secrets.NEXUS_HELM_REPO }} \
            --username ${{ secrets.NEXUS_HELM_REPO_USER }} \
            --password ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
          export CURRENT_VER=`helm show chart ./sausage-store-chart | yq '.version'`
          export NEW_VER=`echo "$CURRENT_VER" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g'`
          yq e -i '.version = env(NEW_VER)' sausage-store-chart/Chart.yaml
          cd sausage-store-chart
          helm cm-push --version=$NEW_VER --context-path="/repository/guzov-sem2-helm" . chartmuseum

  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: add_helm_chart_to_nexus

      steps:
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add helm repo
        run: |
          helm repo add chartmuseum ${{ secrets.NEXUS_HELM_REPO }} \
            --username ${{ secrets.NEXUS_HELM_REPO_USER }} \
            --password ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
          helm repo update
          echo "$KUBE_CONFIG" > kubeconf
          chmod 600 kubeconf
          export VERSION=$(helm show chart chartmuseum/sausage-store | yq '.version')
          helm upgrade --install sausage-store chartmuseum/sausage-store \
            --version $VERSION \
            --kubeconfig ./kubeconf  \
            --namespace '${{ secrets.KUBE_NAMESPACE }}' \
            --set backend_report.image_tag=${{ github.sha }} \
            --set backend.image_tag=${{ github.sha }} \
            --set frontend.image_tag=${{ github.sha }}
          rm -rf kubeconf
